### ISSUE TITLE
getEdgeVertices not necessarily correct

### ISSUE THREAD

**Issue by l-hoang** [Podsiadlo/TerrainMeshGenerator#3]
getEdgeVertices in Production.h assumes that an edge's ID correlates to the vertices it connects. However, this isn't necessarily the case.

For example, in the initial graph, there is an edge between nodes 1 and 3. This is the second edge created (i.e. id 1), so getEdgeVertices will return 1, 2, which is incorrect. 

This assumption may not hold after you begin adding edges to the graph as well.

**Comment by Podsiadlo** [comment]
Ah, that's the thing I haven't told you. Methods in Production.h are returning ids in reference to the current triangle. It means that when getEdgeVertices(...) returns 1, 2, then ProductionState.getVertices()[1] and  ProductionState.getVertices()[2] are the real nodes.

**Comment by l-hoang** [comment]
I see, makes sense.

So the following assumptions are being made/held, correct?:

1) 0, 1, or 2 is being passed into getEdgeVertices
2) In a hyperedge/ProductionState, the edges connect 0->1, 1->2, and 2->0.
3) Related to (2), that also means that 0's neutral is 2, 1's neutral is 0, and 2's neutral is 1.

**Comment by Podsiadlo** [comment]
Right, this is how it works.

pt., 28 lut 2020, 21:19 użytkownik Loc Hoang <notifications@github.com>
napisał:

**Comment by l-hoang** [comment]
I've been looking at the code a bit more, and I don't think this invariant always holds.

1) When you construct the production state, you call ConnectivityManager's getNeighbors on a hyperedge node. I'm not sure how the underlying MorphGraph works, but it's possible that the vertex order you get isn't the 0->1, 1->2, 2->0 order.

2) Shared triangle edges will break this invariant. Consider the first 2 triangles you add in the GraphGenerator code. Per the createInterior call, this is the assumed edge order.

- 0->1, 1->3, 3->0
- 0->3, 3->2, 2->0.

The problem is that both 0->3 and 3->0 don't exist at the same time, so the triangle is actually
3->0, 3->2, 2->0 (wedge pattern).

This issue exists in the createNodeOnEdge call as well in Production.h: the new edges being added to connect to the broken edge node will cause 1 of the triangles to not following the cyclic edge order.

Is this all correct, or am I missing something?
