### ISSUE TITLE
getNeutralVertex not necessarily correct

### ISSUE THREAD

**Issue by l-hoang** [Podsiadlo/TerrainMeshGenerator#4]
getNeutralVertex in Production.h assumes that triangles are always in triples when this is not necessarily true, especially after new nodes are added which don't necessarily have an order to take advantage of.

I think this can be fixed (similar to getEdgeVertices) by leveraging the ProductionState you are maintaining. It will add some overhead in exchange for being correct.

**Comment by Podsiadlo** [comment]
As I've written in issue #3 comment, this method returns an id in current triangle.
